version: "3"

services: 
  web:
    hostname: bremse.mosaiksoftware.local
    image: mosaiksoftware/php54
    ports: 
      - "8085:80"
    volumes: 
      - webroot:/var/www
    environment:
      PHP_MCM_DEBUG_CONFIG: molle
    networks:
      sag:
        aliases: 
          - web
  mysqldb:
    image: hub.ad.mosaiksoftware.de/sag/mysql
    volumes: 
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sag1234
      MYSQL_USER: sag_stable
      MYSQL_PASSWORD: "54g-4k4d3m13"
      MYSQL_DATABASE: sag-akademie_de_stable
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
     sag:
      aliases: 
        - mysqldb
    ports: 
      - "3309:3306"
  memcache:
    image: memcached
    expose: 
      - "11211"
    command: memcached -m 256 -p 11211 -vvv
    networks:
     sag:
      aliases: 
        - memcache
  sftp:
    image: mosaiksoftware/debian-rssh
    ports:
      - "4001:4001"
    environment:
      SSH_PORT: "4001"
      ALLOW_SFTP: "yes"
      USER: "sag"
      PASSWORD: "sag#2018"
      USER_1: "ms"
      PASSWORD_1: "ms#2018"
    volumes:
      - "webroot:/chroot/home/sag"
volumes:
    webroot: 
      driver: local
      driver_opts: 
        type: nfs
        o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
        device: ":/Users/cholzberger/Projekte/SAG-Akademie-GmbH/SAG-Akademie.de"
    mysql: 
      driver: local
networks:
  sag:

