version: "3"

services: 
  web:
    container_name: sag_beta_www
    hostname: beta.sag-akademie.de
    image: hub.ad.mosaiksoftware.de/sag/www
    ports: 
      - "8082:80"
    environment:
      PHP_MCM_DEBUG_CONFIG: beta.sag-akademie.de
    networks:
      sag:
        aliases: 
          - web
  mysqldb:
    container_name: sag_beta_mysql
    image: hub.ad.mosaiksoftware.de/sag/mysql
    volumes: 
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sag1234
      MYSQL_USER: sag_stable
      MYSQL_PASSWORD: "54g-4k4d3m13"
      MYSQL_DATABASE: sag-akademie_de_stable
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
     sag:
      aliases: 
        - mysqldb
    ports: 
      - "3309:3306"
  memcache:
    container_name: sag_beta_memcache
    image: memcached:1.4.39
    expose: 
      - "11211"
    command: memcached -m 256 -p 11211 -vvv
    networks:
     sag:
      aliases: 
        - memcache
volumes:
    mysql: 
      driver: local
networks:
  sag:

