version: "3"

services: 
  web:
    container_name: sag_${RELEASE_BRANCH}_www
    hostname: www.sag-akademie.de
    build: ./sag-akademie.de/
    image: hub.ad.mosaiksoftware.de/sag/www:${BUILD_BRANCH}${BUILD_VERSION}
    ports: 
      - "8081:80"
    environment:
      PHP_MCM_DEBUG_CONFIG: www.sag-akademie.de
    networks:
      sag:
        aliases: 
          - web
  mysqldb:
    container_name: sag_${RELEASE_BRANCH}_mysql
    image: hub.ad.mosaiksoftware.de/sag/mysql:${BUILD_BRANCH}${BUILD_VERSION}
    build: ./mysql/
    environment:
      MYSQL_ROOT_PASSWORD: sag1234
      MYSQL_USER: sag_stable
      MYSQL_PASSWORD: "54g-4k4d3m13"
      MYSQL_DATABASE: sag-akademie_de_stable
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
     sag:
      aliases: 
        - mysqldb
  memcache:
    container_name: sag_${RELEASE_BRANCH}_memcache
    image: memcached
    expose: 
      - "11211"
    command: memcached -m 1024 -p 11211 -vvv
    networks:
     sag:
      aliases: 
        - memcache
  sftp:
    image: mosaiksoftware/debian-rssh
    ports:
      - "4001:4001"
    environment:
      SSH_PORT: "4001"
      ALLOW_SFTP: "yes"
      USER: "sag"
      PASSWORD: "sag#2018"
      USER_1: "ms"
      PASSWORD_1: "ms#2018"
networks:
  sag:

