<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Buchung extends BaseBuchung
{
 public function setUp()
    {
    	parent::setUp();
		$this->actAs("BuchungTemplate");
		$this->actAs("SoftDelete");
		
		$this->actAs('Versionable', array(
		 'versionColumn' => 'version',
		 'className' => '%CLASS%Version',
		 'auditLog' => true
		 )
		);
    }
	
	public function pinit() {
		if ( $this->seminar_id != 0 ) {
			$this->vdrk_mitglied = $this->Person->Kontakt->vdrk_mitglied;
			$this->kursgebuehr = $this->Seminar->kursgebuehr;
			$this->kosten_allg = $this->Seminar->kosten_allg;
			$this->kosten_refer = $this->Seminar->kosten_refer;
			$this->kosten_unterlagen = $this->Seminar->kosten_unterlagen;
			$this->kosten_verpflegung = $this->Seminar->kosten_verpflegung;
			
			// FIXME: person und kontakt daten  
			// mit einberechnen (vdrk, arbeitsamt etc.)
			$this->nettoep = $this->Seminar->nettoep;
		}
	}
	
}
?>