<?php

/**
 * ClogSeminarArtTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClogSeminarArtTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClogSeminarArtTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClogSeminarArt');
    }
}