<?php

/**
 * ClogSeminarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClogSeminarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClogSeminarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClogSeminar');
    }
}