<?php

/**
 * Download
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
class Download extends BaseDownload
{
	public function setUp() {
		$this->actAs("ChangeCounted");
	}

	public function hasFileTableProxy($fname) {
		$q = Doctrine_Query::create()->from("Download")->where("file LIKE ?", array("%$fname"));

		return $q->count() > 0;
	}
}