<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Formulareintraege extends BaseFormulareintraege
{
	public function setUp() {
		$this->actAs("ChangeCounted");
	}
}
?>