<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HotelBuchung extends BaseHotelBuchung {
	public function setUp() {
		parent::setUp();

		$this->hasOne('Hotel', array (
		'local'=>'hotel_id',
		'foreign'=>'id',
		));

		$this->hasOne('Buchung', array (
		'local'=>'buchung_id',
		'foreign'=>'id',
		));
		$this->actAs("ChangeCounted");
		$this->actAs("ChangeLogged");

		$this->actAs("SoftDelete");
		$this->addListener(new HotelBuchungListener());
		
	}
	
	function pinit($price) {
			$this->zimmerpreis_ez = $price['zimmerpreis_ez']; 
			$this->zimmerpreis_dz = $price['zimmerpreis_dz'];
			$this->fruehstuecks_preis = $price['fruehstuecks_preis'];
			$this->marge = $price['marge'];
	}
	
	function detailedByBuchungIdTableProxy($id) {
		return Doctrine_Query::create()
			->from ("HotelBuchung hotelBuchung")
			->leftJoin ("hotelBuchung.Hotel hotel")
			->where ("hotelBuchung.buchung_id = ?", $id);
	}
}
?>
