<?php

/**
 * InhouseOrtTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InhouseOrtTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InhouseOrtTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InhouseOrt');
    }
}