<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailingSendung extends BaseMailingSendung
{public function setUp() {
	parent::setUp();
	$this->actAs("ChangeCounted");
}
}
?>