<?php

/**
 * Neuigkeit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
class Neuigkeit extends BaseNeuigkeit
{
    public function setUp() {
        parent::setUp();
	$this->actAs("SoftDelete");
        $this->hasOne('XUser as GeaendertVon', array (
            'local'=>'geaendert_von',
            'foreign'=>'id',
            )
        );


		$this->actAs("ChangeCounted");
    }
}