<?php

/**
 * NewsletterAbmeldungSeitAprill2013
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NewsletterAbmeldungSeitAprill2013 extends BaseNewsletterAbmeldungSeitAprill2013
{

}