<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Person extends BasePerson {

	public function setUp() {
		parent::setUp();
		$this->actAs("PersonTemplate");
		$this->actAs('Versionable', array(
		 'versionColumn' => 'version',
		 'className' => '%CLASS%Version',
		 'auditLog' => true
		 )
		);
	}

	function personKontaktQTableProxy() {
		$q = Doctrine_Query::create();
		$q->from('Person Person')
		 ->leftJoin('Person.Kontakt Kontakt');
		return $q;
	}

	function getBuchungen() {
		$q = Doctrine_Query::create();
		$q->from("ViewBuchungPreis buchung")
		 ->leftJoin("buchung.Seminar seminar")
		 ->leftJoin("seminar.SeminarArt seminarArt")
		 ->where("buchung.person_id = ?", $this->id);
		return $q;
	}

	function setPasswort($pw) {
		
	}

}

?>
