<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostInfo extends BasePostInfo
{
	public function setUp() {
		parent::setUp();
		//$this->actAs("ChangeCounted");
	}
}
?>