<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeminarTable extends Doctrine_Table
{
	public function updateKursNr() {
	    $seminare = Doctrine::getTable("ViewFreigegebeneSeminare")->findAll();

	    foreach ( $seminare as $seminar ) {
		$sem = Doctrine::getTable("Seminar")->find($seminar->id);

		$nummer = Doctrine::getTable("SeminarArtNummer")->getNextNumber($sem->seminar_art_id, $seminar->jahr);

		$sem->kursnr = $seminar->jahr_kurz . "-" . $sem->seminar_art_id . "-" . sprintf("%02d", $nummer) . "-" . $seminar->standort_kuerzel;
		$sem->kursnr_vergeben = $nummer;
		$sem->save();
	    }
	}
}
?>