<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StandortTable extends Doctrine_Table
{
            function detailed($id = false) {
		$q = Doctrine_Query::create()
		->from('Standort a')
                ->leftJoin('a.GeaendertVon user');
		if($id != false) {
		    MosaikDebug::msg("detailed($id) is deprecated","Standort");
		    $q->where('a.id = ?', $id);
		}else{
		    $q->where('a.id = ?');
		}
		//->andWhere('buchungen.storno_datum = ?', '0000-00-00');
		return $q;
	}
	function getAll(){
	    $q = Doctrine_Query::create()
	    ->from('Standort a')
	    ->leftJoin('a.GeaendertVon user');
	    return $q;
	}
}
?>