<?php

/**
 * ViewInhousePreisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViewInhousePreisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViewInhousePreisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ViewInhousePreis');
    }
}