<?php

/**
 * ViewFeiertagR
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class ViewFeiertagR extends BaseViewFeiertagR
{
	function getBundeslandTableProxy($blid, $year=false)
	{
		$q = Doctrine_Query::create();
		$q->from("ViewFeiertagR")
		->where ("ViewFeiertagR.uid = ?", $blid);
		if($year != false)
		{
		$q->where("ViewFeiertagR.datum >= '".trim($year)."-01-01'");
		$q->andWhere("ViewFeiertagR.datum <= '".trim($year)."-12-31'");
		}
		return $q;
	}
}