<?php

/**
 * ViewInhouseSeminarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViewInhouseSeminarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViewInhouseSeminarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ViewInhouseSeminar');
    }
}