<?php

/**
 * ViewKontakt
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class ViewKontakt extends BaseViewKontakt {

    public function setUp() {
	parent::setUp();
    	$this->actAs("KontaktTemplate");
	$this->hasOne('XUser as GeaendertVon', array (
	    'local'=>'geaendert_von',
	    'foreign'=>'id',
	    )
	);
	$this->hasMany('Person as Personen', array(
	    'local' => 'id',
	    'foreign' => 'kontakt_id'
	    )
	);

	$this->hasMany('KontaktAlias as Alias', array(
	    'local'=>'id',
	    'foreign' => 'kontakt_id'
	    )
	);

	$this->hasOne('XUser as AngelegtVon', array (
	    'local'=>'angelegt_user_id',
	    'foreign'=>'id',
	    )
	);
    }

  
}