<?php

/**
 * ViewBuchungTeilnehmerEmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
class ViewBuchungTeilnehmerEmail extends BaseViewBuchungTeilnehmerEmail
{
    function getListBySeminarIdTableProxy($id) {
	$q = Doctrine_Query::create()->from ("ViewBuchungTeilnehmerEmail email")
		->where("email.seminar_id = ?", ($id))
		->andWhere("email.email <> ''");
	return $q;
    }
}