<?php

/**
 * ViewSeminarTageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViewSeminarTageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViewSeminarTageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ViewSeminarTage');
    }
}