<?php

/**
 * ViewAkquiseKontaktR
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class ViewAkquiseKontaktR extends BaseViewAkquiseKontaktR
{
    function detailSearchTableProxy($string) {
		$string = strtolower(trim(utf8_decode($string)));

		if (strlen($string) == 2) {
			$q = Doctrine_Query::create()
			->from("ViewAkquiseKontaktR k")
			->where("k.firma LIKE ? OR k.alias LIKE ?", array($string,$string));
		} else {
			$q = Doctrine_Query::create()
			->from("ViewAkquiseKontaktR k")
			->where("( k.firma LIKE ? OR k.alias LIKE ?)", array($string,$string));

			$data = explode(" ", $string);
			foreach ( $data as $d ) {
				$d = utf8_encode($d);

				if ( !empty($d)) {
					$q->orWhere("k.firma <> '' AND k.firma LIKE ?", "%$d%");
				//	$q->orWhere("k.alias <> '' AND k.alias LIKE ?", "%$d%");
				}
			}
		}
		return $q;
	}

	function searchTableProxy($string) {
		$string = strtolower(trim(utf8_decode($string)));
		
		if (strlen($string) == 2) {
			$q = Doctrine_Query::create()
			->select('k.id')
			->from("ViewAkquiseKontaktR k")
			->where("( k.firma LIKE ? or k.alias LIKE ?)",array ($string, $string));
		} else {
			$q = Doctrine_Query::create()
			->select('k.id')
			->from("ViewAkquiseKontaktR k")
			->where("k.firma LIKE ? OR k.alias LIKE ?", array($string,$string));
			
			$data = explode(" ", $string);
			foreach ( $data as $d ) {
				$d = utf8_encode($d); 
				
				if ( !empty($d)) {
					$q->orWhere("k.firma <> '' AND k.firma LIKE ?", "%$d%");
				//	$q->orWhere("k.alias <> '' AND k.alias LIKE ?", "%$d%");
				}
			}
		}
		return $q->fetchArray();
	}

	
	 function detailedInTableProxy($ids) {

		$q = Doctrine_Query::create()
		->from('ViewAkquiseKontaktR a')
		->whereIn('a.id', $ids);
		return $q;
	}
        function advancedSearchTableProxy($array) {
        $q = Doctrine_Query::create();

	$q->from( "ViewAkquiseKontaktR a" );
        MosaikDebug::msg($array, "Ausgabe:");
        $first = true;
        $tmp_where = "";
        $q->where("1 = 0");
        foreach($array as $key => $value)
        {
           if($value == "or") {
                $q->orWhere($tmp_where);
                $tmp_where = "";
                $first = true;
           }else{
               $exp = explode(";", $value);
               $val_array = explode(":", $exp[0]);
               switch($val_array[1]) {
                case "string":
                        $exp[2] = "%".$exp[2]."%";
                    break;
                case "date":
                        $exp[2] = mysqlDateFromLocal($exp[2]);
                    break;
                case "datetime":
                        $exp[2] = mysqlDatetimeFromLocal($exp[2]);
                    break;
              }
               $search = "'".$exp[2]."'";
               if($first)
               {
                   $tmp_where .= "a.".$val_array[0]." ".$exp[1]." ".$search;
                   $first = false;
               }else{
                  $tmp_where .= " AND a.".$val_array[0]." ".$exp[1]." ".$search;
               }
           }
        }
        $q->orWhere($tmp_where);

	return $q;
    }
}