<?php

/**
 * ViewInhouseSeminarArtTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViewInhouseSeminarArtTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViewInhouseSeminarArtTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ViewInhouseSeminarArt');
    }
}