<?php

/**
 * XGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class XGroup extends BaseXGroup
{
	public function setUp() {
		parent::setUp();
		$this->actAs("ChangeCounted");
	}
}