<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class XSettings extends BaseXSettings
{
	public function setUp() {
		parent::setUp();
		$this->actAs("ChangeCounted");
	}
}
?>