<?php

/**
 * XTableVersionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class XTableVersionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object XTableVersionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('XTableVersion');
    }

	/**
	 * Increment version number for $table by one
	 */
	function increment ( $table ) {
		$t = Doctrine::getTable("XTableVersion")->findByDql("table_name = ?",$table)->getFirst();
		 if (!is_object($t)) {
             $t = new XTableVersion();
             $t->table_name = $table;
             $t->version = 1;
             $t->last_change = currentMysqlDatetime();
		 } else {
			$t->version = $t->version +1;
			$t->last_change = currentMysqlDatetime();
		 }

		$t->save();
	}
}
