version: "3"

services:
  proxy:
    image: mitmproxy/mitmproxy
    command: "mitmweb --mode reverse:http://web:80 --set web_debug=true --set web_iface='' --set keep_host_header=true"
    ports: 
      - "8085:8080"
      - "8087:8081"
    networks:
      sag:
        aliases:
          - proxy
  web:
    hostname: bremse.mosaiksoftware.local
    image: www7
    ports: 
      - "8086:80"
      - "9001:9000"
    volumes: 
      - webroot:/var/www
    environment:
      PHP_MCM_DEBUG_CONFIG: molle
      PHP_MEMORY_LIMIT: 0
      PHP_MAX_EXECUTION_TIME: 360
    networks:
      sag:
        aliases: 
          - web
  mysqldb:
    image: sagmysql
    volumes: 
      - mysql8:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sag1234
      MYSQL_USER: sag_stable
      MYSQL_PASSWORD: "54g-4k4d3m13"
      MYSQL_DATABASE: sag-akademie_de_stable
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    networks:
     sag:
      aliases: 
        - mysqldb
    ports: 
      - "3309:3306"
  memcache:
    image: memcached
    expose: 
      - "11211"
    command: memcached -m 512 -I 10m -p 11211 -vvv
    networks:
     sag:
      aliases: 
        - memcache
  sftp:
    image: mosaiksoftware/debian-rssh
    ports:
      - "4001:4001"
    environment:
      SSH_PORT: "4001"
      ALLOW_SFTP: "yes"
      USER: "sag"
      PASSWORD: "sag#2018"
      USER_1: "ms"
      PASSWORD_1: "ms#2018"
    volumes:
      - "webroot:/chroot/home/sag"
volumes:
    webroot: 
      driver: local
      driver_opts: 
        type: nfs
        o: addr=192.168.254.10,rw,nolock,hard,nointr,nfsvers=3
        device: ":/mnt/op/home/MSDOM/cholzberger/Projekte/SAG-Akademie-GmbH/SAG-Akademie.de"
    mysql8: 
      driver: local
networks:
  sag:

