version: "3"

services: 
  web:
    volumes: 
      - ${PROJECT_HOME}/_state/img:/static/img
      - ${PROJECT_HOME}/sag-akademie.de:/var/www
      - ${PROJECT_HOME}/_state/img:/var/www/img
      - ${PROJECT_HOME}/_state/pdf:/var/www/pdf
      - resources_pdf:/var/www/resources/pdf
      - logs:/var/log/apache2
      - logs:/var/www/resources/log
  mysqldb:
    volumes: 
      - mysql:/var/lib/mysql
  matomo:
    volumes: 
      - matomo:/bitnami
volumes:
    matomo: 
      driver: local
    mysql: 
      driver: local
    resources_pdf:
      driver: local
    logs: 
      driver: local
